system_variable_list = [ ('audit_log_buffer_size', '', False, ['Logging/Audit']),
  ('audit_log_connection_policy', '', True, ['Logging/Audit']),
  ('audit_log_current_session', '', False, []),
  ('audit_log_exclude_accounts', '', True, ['Logging/Audit']),
  ('audit_log_file', '', False, ['Logging/Audit']),
  ('audit_log_flush', '', True, []),
  ('audit_log_format', '', False, ['Logging/Audit']),
  ('audit_log_include_accounts', '', True, ['Logging/Audit']),
  ('audit_log_policy', '', True, ['Logging/Audit']),
  ('audit_log_rotate_on_size', '', True, ['Logging/Audit']),
  ('audit_log_statement_policy', '', True, ['Logging/Audit']),
  ('audit_log_strategy', '', False, ['Logging/Audit']),
  ('auto_generate_certs', '', False, ['Security/Security']),
  ('auto_increment_increment', '', True, []),
  ('auto_increment_offset', '', True, []),
  ('autocommit', '', True, ['General/Transactions']),
  ('automatic_sp_privileges', '', True, []),
  ('avoid_temporal_upgrade', '', True, []),
  ('back_log', '', False, []),
  ('backup_elevation', '', False, ['General/Backup']),
  ('backup_history_log', '', True, ['General/Backup']),
  ('backup_history_log_file', '', True, ['General/Backup']),
  ('backup_progress_log', '', True, ['General/Backup']),
  ('backup_progress_log_file', '', True, ['General/Backup']),
  ('backup_wait_timeout', '', True, []),
  ('backupdir', '', True, ['General/Backup']),
  ('basedir', '', False, ['General/Directories']),
  ('bdb-data-direct', '', False, []),
  ('bdb-home', '', False, []),
  ('bdb-lock-detect', '', False, []),
  ('bdb-log-direct', '', False, []),
  ('bdb-logdir', '', False, []),
  ('bdb-shared-data', '', False, []),
  ('bdb-tmpdir', '', False, []),
  ('bdb_cache_size', '', False, []),
  ('bdb_log_buffer_size', '', False, []),
  ('bdb_max_lock', '', False, []),
  ('big-tables', '', True, []),
  ('bind-address', '', False, []),
  ('binlog-format', '', True, []),
  ('binlog_cache_size', '', True, ['Logging/Binlog Options']),
  ('binlog_checksum', '', True, []),
  ( 'binlog_direct_non_transactional_updates',
    '',
    True,
    ['Logging/Binlog Options']),
  ('binlog_error_action', '', True, ['Logging/Binlog Options']),
  ('binlog_group_commit_sync_delay', '', True, ['Logging/Binlog Options']),
  ( 'binlog_group_commit_sync_no_delay_count',
    '',
    True,
    ['Logging/Binlog Options']),
  ('binlog_gtid_simple_recovery', '', False, ['Logging/Binlog Options']),
  ('binlog_max_flush_queue_time', '', True, []),
  ('binlog_order_commits', '', True, []),
  ('binlog_row_image', '', True, ['Logging/Binlog Options']),
  ('binlog_rows_query_log_events', '', True, []),
  ('binlog_stmt_cache_size', '', True, ['Logging/Binlog Options']),
  ('binlogging_impossible_mode', '', True, ['Logging/Binlog Options']),
  ('block_encryption_mode', '', True, ['Security/Security']),
  ('bulk_insert_buffer_size', '', True, ['Advanced/Various']),
  ('character-set-filesystem', '', True, []),
  ('character-set-server', '', True, []),
  ('character-sets-dir', '', False, []),
  ('character_set', '', False, []),
  ('character_set_client', '', True, []),
  ('character_set_connection', '', True, []),
  ('character_set_database', '', True, []),
  ('character_set_results', '', True, []),
  ('character_set_system', '', False, []),
  ('check_proxy_users', '', True, []),
  ('collation-server', '', True, []),
  ('collation_connection', '', True, []),
  ('collation_database', '', True, []),
  ('completion_type', '', True, ['Advanced/Transactions']),
  ('concurrent_insert', '', True, ['MyISAM/General']),
  ('connect_timeout', '', True, ['Networking/Timeout Settings']),
  ('core_file', '', False, []),
  ('create_old_temporals', '', False, []),
  ('daemon_memcached_enable_binlog', '', False, ['Other/Memcached']),
  ('daemon_memcached_engine_lib_name', '', False, ['Other/Memcached']),
  ('daemon_memcached_engine_lib_path', '', False, ['Other/Memcached']),
  ('daemon_memcached_option', '', False, ['Other/Memcached']),
  ('daemon_memcached_r_batch_size', '', False, ['Other/Memcached']),
  ('daemon_memcached_w_batch_size', '', False, ['Other/Memcached']),
  ('datadir', '', False, ['General/Directories']),
  ('date_format', '', False, []),
  ('datetime_format', '', False, []),
  ('debug', '', True, ['Advanced/General']),
  ('debug_sync', '', True, []),
  ('default-storage-engine', '', True, []),
  ('default_authentication_plugin', '', False, ['Security/Authentication']),
  ('default_password_lifetime', '', True, ['Security/Authentication']),
  ('default_tmp_storage_engine', '', True, ['General/General']),
  ('default_week_format', '', True, ['General/International']),
  ('delay-key-write', '', True, []),
  ('delayed_insert_limit', '', True, ['Advanced/Insert delayed settings']),
  ('delayed_insert_timeout', '', True, ['Advanced/Insert delayed settings']),
  ('delayed_queue_size', '', True, ['Advanced/Insert delayed settings']),
  ('disable-gtid-unsafe-statements', '', False, ['Replication/General']),
  ('disable_gtid_unsafe_statements', '', False, ['Replication/General']),
  ('disabled_storage_engines', '', False, []),
  ('disconnect_on_expired_password', '', False, ['Security/Authentication']),
  ('div_precision_increment', '', True, ['Advanced/General']),
  ('end_markers_in_json', '', True, []),
  ('enforce-gtid-consistency', '', False, ['Replication/General']),
  ('enforce_gtid_consistency', '', False, ['Replication/General']),
  ('engine-condition-pushdown', '', True, []),
  ('eq_range_index_dive_limit', '', True, []),
  ('error_count', '', False, []),
  ('event-scheduler', '', True, []),
  ('executed_gtids_compression_period', '', True, []),
  ('expire_logs_days', '', True, ['Logging/Advanced log options']),
  ('explicit_defaults_for_timestamp', '', False, ['General/SQL']),
  ('external_user', '', False, []),
  ('falcon_checkpoint_schedule', '', True, []),
  ('falcon_checksums', '', True, []),
  ('falcon_consistent_read', '', True, []),
  ('falcon_debug_mask', '', True, []),
  ('falcon_debug_server', '', False, []),
  ('falcon_disable_fsync', '', True, []),
  ('falcon_gopher_threads', '', False, []),
  ('falcon_index_chill_threshold', '', True, []),
  ('falcon_initial_allocation', '', True, []),
  ('falcon_io_threads', '', True, []),
  ('falcon_large_blob_threshold', '', False, []),
  ('falcon_lock_wait_timeout', '', True, []),
  ('falcon_max_transaction_backlog', '', True, []),
  ('falcon_page_cache_size', '', False, []),
  ('falcon_page_size', '', False, []),
  ('falcon_record_chill_threshold', '', True, []),
  ('falcon_record_memory_max', '', True, []),
  ('falcon_record_scavenge_floor', '', True, []),
  ('falcon_record_scavenge_threshold', '', True, []),
  ('falcon_scavenge_schedule', '', False, []),
  ('falcon_serial_log_buffers', '', False, []),
  ('falcon_serial_log_dir', '', False, []),
  ('falcon_serial_log_priority', '', True, []),
  ('falcon_support_xa', '', False, []),
  ('falcon_use_deferred_index_hash', '', False, []),
  ('falcon_use_sectorcache', '', False, []),
  ('falcon_use_supernodes', '', False, []),
  ('flush', '', True, ['Advanced/General']),
  ('flush_time', '', True, ['Advanced/General']),
  ('foreign_key_checks', '', True, []),
  ('ft_boolean_syntax', '', True, ['MyISAM/Fulltext search']),
  ('ft_max_word_len', '', False, ['MyISAM/Fulltext search']),
  ('ft_min_word_len', '', False, ['MyISAM/Fulltext search']),
  ('ft_query_expansion_limit', '', False, ['MyISAM/Fulltext search']),
  ('ft_stopword_file', '', False, ['MyISAM/Fulltext search']),
  ('general-log', '', True, []),
  ('general_log_file', '', True, ['Logging/General']),
  ('group_concat_max_len', '', True, ['Advanced/Various']),
  ('gtid-mode', '', False, []),
  ('gtid_done', '', False, []),
  ('gtid_executed', '', False, []),
  ('gtid_executed_compression_period', '', True, []),
  ('gtid_lost', '', False, []),
  ('gtid_mode', '', False, []),
  ('gtid_next', '', True, []),
  ('gtid_owned', '', False, []),
  ('gtid_purged', '', True, []),
  ('have_archive', '', False, []),
  ('have_bdb', '', False, []),
  ('have_blackhole_engine', '', False, []),
  ('have_community_features', '', False, []),
  ('have_compress', '', False, []),
  ('have_crypt', '', False, []),
  ('have_csv', '', False, []),
  ('have_dynamic_loading', '', False, []),
  ('have_example_engine', '', False, []),
  ('have_federated_engine', '', False, []),
  ('have_geometry', '', False, []),
  ('have_innodb', '', False, []),
  ('have_isam', '', False, []),
  ('have_merge_engine', '', False, []),
  ('have_ndbcluster', '', False, []),
  ('have_openssl', '', False, []),
  ('have_partition_engine', '', False, []),
  ('have_partitioning', '', False, []),
  ('have_profiling', '', False, []),
  ('have_query_cache', '', False, []),
  ('have_raid', '', False, []),
  ('have_row_based_replication', '', False, []),
  ('have_rtree_keys', '', False, []),
  ('have_ssl', '', False, []),
  ('have_statement_timeout', '', False, []),
  ('have_symlink', '', False, []),
  ('host_cache_size', '', True, []),
  ('hostname', '', False, []),
  ('identity', '', True, []),
  ('ignore-builtin-innodb', '', False, []),
  ('ignore_db_dirs', '', False, []),
  ('init-file', '', False, []),
  ('init_connect', '', True, ['Advanced/General']),
  ('init_slave', '', True, ['Advanced/General', 'Replication/Slave']),
  ('innodb_adaptive_flushing', '', True, ['InnoDB/General']),
  ('innodb_adaptive_flushing_lwm', '', True, ['InnoDB/General']),
  ('innodb_adaptive_hash_index', '', False, ['InnoDB/General']),
  ('innodb_adaptive_hash_index_parts', '', False, ['InnoDB/General']),
  ('innodb_adaptive_max_sleep_delay', '', True, ['InnoDB/General']),
  ('innodb_api_bk_commit_interval', '', True, ['InnoDB/General']),
  ('innodb_api_disable_rowlock', '', False, ['InnoDB/General']),
  ('innodb_api_enable_binlog', '', False, ['InnoDB/General']),
  ('innodb_api_enable_mdl', '', False, ['InnoDB/General']),
  ('innodb_api_trx_level', '', True, ['InnoDB/General']),
  ('innodb_autoextend_increment', '', True, ['InnoDB/General']),
  ('innodb_autoinc_lock_mode', '', False, ['InnoDB/General']),
  ('innodb_background_drop_list_empty', '', True, ['InnoDB/General']),
  ('innodb_buffer_pool_awe_mem_mb', '', False, ['InnoDB/Buffer pool']),
  ('innodb_buffer_pool_chunk_size', '', False, ['InnoDB/Buffer pool']),
  ('innodb_buffer_pool_dump_at_shutdown', '', True, ['InnoDB/Buffer pool']),
  ('innodb_buffer_pool_dump_now', '', True, ['InnoDB/Buffer pool']),
  ('innodb_buffer_pool_dump_pct', '', True, ['InnoDB/General']),
  ('innodb_buffer_pool_filename', '', True, ['InnoDB/Buffer pool']),
  ( 'innodb_buffer_pool_instances',
    '',
    False,
    ['InnoDB/Buffer pool', 'InnoDB/Memory']),
  ('innodb_buffer_pool_load_abort', '', True, ['InnoDB/Buffer pool']),
  ('innodb_buffer_pool_load_at_startup', '', False, ['InnoDB/Buffer pool']),
  ('innodb_buffer_pool_load_now', '', True, ['InnoDB/Buffer pool']),
  ( 'innodb_buffer_pool_size',
    '',
    False,
    ['InnoDB/Buffer pool', 'InnoDB/Memory']),
  ('innodb_change_buffer_max_size', '', True, ['InnoDB/General']),
  ('innodb_change_buffering', '', True, ['InnoDB/General']),
  ('innodb_change_buffering_debug', '', True, ['InnoDB/General']),
  ('innodb_checksum_algorithm', '', True, ['InnoDB/General']),
  ('innodb_checksums', '', False, ['InnoDB/General']),
  ('innodb_cmp_per_index_enabled', '', True, ['InnoDB/General']),
  ('innodb_commit_concurrency', '', True, ['InnoDB/General']),
  ('innodb_compress_debug', '', True, ['InnoDB/General']),
  ('innodb_compression_failure_threshold_pct', '', True, ['InnoDB/General']),
  ('innodb_compression_level', '', True, ['InnoDB/General']),
  ('innodb_compression_pad_pct_max', '', True, ['InnoDB/General']),
  ('innodb_concurrency_tickets', '', True, ['InnoDB/General']),
  ('innodb_create_intrinsic', '', True, ['InnoDB/General']),
  ('innodb_data_file_path', '', False, ['InnoDB/Datafiles']),
  ('innodb_data_home_dir', '', False, ['InnoDB/Datafiles']),
  ('innodb_default_row_format', '', True, ['InnoDB/General']),
  ('innodb_disable_sort_file_cache', '', True, ['InnoDB/General']),
  ('innodb_disable_resize_buffer_pool_debug', '', True, ['InnoDB/General']),
  ('innodb_doublewrite', '', False, ['InnoDB/General']),
  ('innodb_extra_dirty_writes', '', False, ['InnoDB/General']),
  ('innodb_fast_shutdown', '', True, ['InnoDB/Various']),
  ('innodb_fil_make_page_dirty_debug', '', True, []),
  ('innodb_file_format', '', True, ['InnoDB/Datafiles']),
  ('innodb_file_format_check', '', True, ['InnoDB/Datafiles']),
  ('innodb_file_format_max', '', True, ['InnoDB/Datafiles']),
  ('innodb_file_io_threads', '', False, ['InnoDB/General']),
  ('innodb_file_per_table', '', False, ['InnoDB/General']),
  ('innodb_fill_factor', '', True, ['InnoDB/General']),
  ('innodb_flush_log_at_timeout', '', True, []),
  ('innodb_flush_log_at_trx_commit', '', True, ['InnoDB/Logfiles']),
  ('innodb_flush_method', '', False, ['InnoDB/Logfiles']),
  ('innodb_flush_neighbors', '', True, ['InnoDB/Logfiles']),
  ('innodb_flush_sync', '', True, ['InnoDB/Logfiles']),
  ('innodb_flushing_avg_loops', '', True, ['InnoDB/General']),
  ('innodb_force_load_corrupted', '', False, ['InnoDB/General']),
  ('innodb_force_recovery', '', False, ['InnoDB/General']),
  ('innodb_ft_aux_table', '', True, ['InnoDB/Fulltext search']),
  ('innodb_ft_cache_size', '', False, ['InnoDB/Fulltext search']),
  ('innodb_ft_enable_diag_print', '', True, ['InnoDB/Fulltext search']),
  ('innodb_ft_enable_stopword', '', True, ['InnoDB/Fulltext search']),
  ('innodb_ft_max_token_size', '', False, ['InnoDB/Fulltext search']),
  ('innodb_ft_min_token_size', '', False, ['InnoDB/Fulltext search']),
  ('innodb_ft_num_word_optimize', '', True, ['InnoDB/Fulltext search']),
  ('innodb_ft_result_cache_limit', '', True, ['InnoDB/Fulltext search']),
  ('innodb_ft_server_stopword_table', '', True, ['InnoDB/Fulltext search']),
  ('innodb_ft_sort_pll_degree', '', False, ['InnoDB/Fulltext search']),
  ('innodb_ft_total_cache_size', '', False, ['InnoDB/Fulltext search']),
  ('innodb_ft_user_stopword_table', '', True, ['InnoDB/Fulltext search']),
  ('innodb_io_capacity', '', False, ['InnoDB/General']),
  ('innodb_io_capacity_max', '', True, ['InnoDB/General']),
  ('innodb_large_prefix', '', True, ['InnoDB/General']),
  ('innodb_limit_optimistic_insert_debug', '', True, ['InnoDB/General']),
  ('innodb_lock_wait_timeout', '', False, ['InnoDB/General']),
  ('innodb_locks_unsafe_for_binlog', '', False, ['InnoDB/General']),
  ('innodb_log_arch_dir', '', False, ['InnoDB/Logfiles']),
  ('innodb_log_archive', '', False, ['InnoDB/Logfiles']),
  ('innodb_log_buffer_size', '', False, ['InnoDB/Logfiles']),
  ('innodb_log_checksum_algorithm', '', True, ['InnoDB/Logfiles']),
  ('innodb_log_checksums', '', True, ['InnoDB/Logfiles']),
  ('innodb_log_compressed_pages', '', True, ['InnoDB/Logfiles']),
  ('innodb_log_file_size', '', False, ['InnoDB/Logfiles']),
  ('innodb_log_files_in_group', '', False, ['InnoDB/Logfiles']),
  ('innodb_log_group_home_dir', '', False, ['InnoDB/Logfiles']),
  ('innodb_log_write_ahead_size', '', True, ['InnoDB/Logfiles']),
  ('innodb_lru_scan_depth', '', True, ['InnoDB/General']),
  ('innodb_max_dirty_pages_pct', '', True, ['InnoDB/General']),
  ('innodb_max_dirty_pages_pct_lwm', '', True, ['InnoDB/General']),
  ('innodb_max_merged_io', '', False, ['InnoDB/General']),
  ('innodb_max_purge_lag', '', True, ['InnoDB/General']),
  ('innodb_max_purge_lag_delay', '', True, ['InnoDB/General']),
  ('innodb_max_undo_log_size', '', True, ['InnoDB/General']),
  ('innodb_additional_mem_pool_size', '', False, ['InnoDB/Memory']),
  ('innodb_merge_threshold_set_all_debug', '', True, []),
  ('innodb_mirrored_log_groups', '', False, ['InnoDB/Logfiles']),
  ('innodb_monitor_disable', '', True, ['InnoDB/General']),
  ('innodb_monitor_enable', '', True, ['InnoDB/General']),
  ('innodb_monitor_reset', '', True, ['InnoDB/General']),
  ('innodb_monitor_reset_all', '', True, ['InnoDB/General']),
  ('innodb_numa_interleave', '', False, ['InnoDB/General']),
  ('innodb_old_blocks_pct', '', True, ['InnoDB/General']),
  ('innodb_old_blocks_time', '', True, ['InnoDB/General']),
  ( 'innodb_online_alter_log_max_size',
    '',
    True,
    ['InnoDB/General', 'InnoDB/Logfiles']),
  ('innodb_open_files', '', False, ['InnoDB/General']),
  ( 'innodb_optimize_fulltext_only',
    '',
    True,
    ['InnoDB/Fulltext search', 'InnoDB/General']),
  ('innodb_optimize_point_storage', '', True, ['InnoDB/General']),
  ('innodb_page_cleaners', '', False, ['InnoDB/Memory']),
  ('innodb_page_size', '', False, ['InnoDB/Memory']),
  ('innodb_print_all_deadlocks', '', True, ['InnoDB/General']),
  ('innodb_purge_batch_size', '', True, ['InnoDB/General']),
  ('innodb_purge_rseg_truncate_frequency', '', True, ['InnoDB/General']),
  ('innodb_purge_threads', '', False, ['InnoDB/General']),
  ('innodb_random_read_ahead', '', True, ['InnoDB/General']),
  ('innodb_read_ahead_threshold', '', True, ['InnoDB/General']),
  ('innodb_read_io_threads', '', False, ['InnoDB/General']),
  ('innodb_read_only', '', False, ['InnoDB/General']),
  ('innodb_replication_delay', '', True, ['InnoDB/General']),
  ('innodb_rollback_on_timeout', '', False, ['InnoDB/General']),
  ('innodb_rollback_segments', '', True, ['InnoDB/General']),
  ('innodb_saved_page_number_debug', '', True, ['InnoDB/General']),
  ('innodb_sort_buffer_size', '', False, ['InnoDB/General', 'InnoDB/Memory']),
  ('innodb_spin_wait_delay', '', True, ['InnoDB/General']),
  ('innodb_stats_auto_recalc', '', True, ['InnoDB/General']),
  ('innodb_stats_method', '', True, ['InnoDB/General']),
  ('innodb_stats_on_metadata', '', False, ['InnoDB/General']),
  ('innodb_stats_persistent', '', True, ['InnoDB/General']),
  ('innodb_stats_persistent_sample_pages', '', True, ['InnoDB/General']),
  ('innodb_stats_sample_pages', '', True, ['InnoDB/General']),
  ('innodb_stats_transient_sample_pages', '', True, ['InnoDB/General']),
  ('innodb_status_output', '', True, ['InnoDB/General']),
  ('innodb_status_output_locks', '', True, ['InnoDB/General']),
  ('innodb_strict_mode', '', True, ['InnoDB/General']),
  ('innodb_support_xa', '', True, ['InnoDB/General']),
  ('innodb_sync_array_size', '', False, ['InnoDB/General']),
  ('innodb_sync_spin_loops', '', True, ['InnoDB/General']),
  ('innodb_sync_debug', '', False, ['InnoDB/General']),
  ('innodb_table_locks', '', True, ['InnoDB/General']),
  ('innodb_temp_data_file_path', '', False, ['InnoDB/General']),
  ('innodb_tmpdir', '', True, ['InnoDB/General']),
  ('innodb_thread_concurrency', '', True, ['InnoDB/General']),
  ('innodb_thread_concurrency_timer_based', '', False, ['InnoDB/General']),
  ('innodb_thread_sleep_delay', '', True, ['InnoDB/General']),
  ('innodb_trx_purge_view_update_only_debug', '', True, ['InnoDB/General']),
  ('innodb_trx_rseg_n_slots_debug', '', True, ['InnoDB/General']),
  ('innodb_undo_directory', '', False, ['InnoDB/General', 'InnoDB/Logfiles']),
  ( 'innodb_undo_log_truncate',
    '',
    True,
    ['InnoDB/General', 'InnoDB/Logfiles']),
  ('innodb_undo_logs', '', True, ['InnoDB/General', 'InnoDB/Logfiles']),
  ('innodb_undo_tablespaces', '', False, ['InnoDB/General']),
  ('innodb_use_legacy_cardinality_algorithm', '', True, ['InnoDB/General']),
  ('innodb_use_native_aio', '', False, ['InnoDB/General']),
  ('innodb_use_sys_malloc', '', False, ['InnoDB/General']),
  ('innodb_version', '', False, []),
  ('innodb_write_io_threads', '', False, ['InnoDB/General']),
  ('insert_id', '', True, []),
  ('interactive_timeout', '', True, ['Networking/Timeout Settings']),
  ('internal_tmp_disk_storage_engine', '', True, []),
  ('join_buffer_size', '', True, ['General/Memory usage']),
  ('join_cache_level', '', True, ['General/Memory usage']),
  ('keep_files_on_create', '', True, ['MyISAM/General']),
  ('key_buffer_size', '', True, ['MyISAM/General']),
  ('key_cache_age_threshold', '', True, ['MyISAM/General']),
  ('key_cache_block_size', '', True, ['Advanced/Various']),
  ('key_cache_division_limit', '', True, ['Advanced/Various']),
  ('keyring_file_data', '', True, []),
  ('language', '', False, ['General/International']),
  ('large-pages', '', False, []),
  ('large_files_support', '', False, []),
  ('large_page_size', '', False, []),
  ('last_insert_id', '', True, []),
  ('lc-messages', '', True, []),
  ('lc-messages-dir', '', False, []),
  ('lc_time_names', '', True, []),
  ('license', '', False, []),
  ('local_infile', '', True, []),
  ('lock_wait_timeout', '', True, ['General/General']),
  ('locked_in_memory', '', False, []),
  ('log', '', False, ['Logging/General']),
  ('log-backup-output', '', True, []),
  ('log-bin', '', False, []),
  ('log-bin-trust-function-creators', '', True, []),
  ('log-bin-trust-routine-creators', '', True, []),
  ('log-bin-use-v1-row-events', '', False, ['Logging/Binlog Options']),
  ('log-error', '', False, []),
  ('log-output', '', True, []),
  ('log-queries-not-using-indexes', '', True, []),
  ('log-slave-updates', '', False, ['Logging/General']),
  ('log-slow-queries', '', False, []),
  ('log-warnings', '', True, []),
  ('log_backward_compatible_user_definitions', '', True, ['Logging/General']),
  ('log_bin', '', False, []),
  ('log_bin_basename', '', False, []),
  ('log_bin_index', '', False, []),
  ('log_bin_use_v1_row_events', '', False, ['Logging/Binlog Options']),
  ('log_builtin_as_identified_by_password', '', True, ['Logging/General']),
  ('log_error_verbosity', '', True, ['Logging/General']),
  ('log_slave_updates', '', False, ['Logging/General']),
  ('log_slow_admin_statements', '', True, []),
  ('log_slow_slave_statements', '', True, []),
  ('log_statements_unsafe_for_binlog', '', True, []),
  ('log_syslog', '', True, ['Logging/General']),
  ('log_syslog_facility', '', True, ['Logging/General']),
  ('log_syslog_include_pid', '', True, ['Logging/General']),
  ('log_syslog_tag', '', True, ['Logging/General']),
  ('log_throttle_queries_not_using_indexes', '', True, []),
  ('log_timestamps', '', True, ['Logging/General']),
  ('long_query_time', '', True, ['Logging/Slow query log options']),
  ('low-priority-updates', '', True, []),
  ('lower_case_file_system', '', False, []),
  ('lower_case_table_names', '', False, ['General/System']),
  ('maria-block-size', '', False, []),
  ('maria-checkpoint-interval', '', True, []),
  ('maria-log-file-size', '', True, []),
  ('maria-log-purge-type', '', True, []),
  ('maria-max-sort-file-size', '', True, []),
  ('maria-page-checksum', '', True, []),
  ('maria-pagecache-age-threshold', '', True, []),
  ('maria-pagecache-buffer-size', '', False, []),
  ('maria-pagecache-division-limit', '', True, []),
  ('maria-recover', '', True, []),
  ('maria-repair-threads', '', True, []),
  ('maria-sort-buffer-size', '', True, []),
  ('maria-stats-method', '', True, []),
  ('maria-sync-log-dir', '', True, []),
  ('master_info_repository', '', True, ['Replication/Master']),
  ('master_verify_checksum', '', True, []),
  ('max_allowed_packet', '', True, ['Networking/Data / Memory size']),
  ('max_binlog_cache_size', '', True, ['Logging/Binlog Options']),
  ('max_binlog_size', '', True, ['Logging/Binlog Options']),
  ('max_binlog_stmt_cache_size', '', True, ['Logging/Binlog Options']),
  ('max_connect_errors', '', True, ['Networking/Advanced']),
  ('max_connections', '', True, ['Networking/Advanced']),
  ('max_delayed_threads', '', True, ['Advanced/Insert delayed settings']),
  ('max_digest_length', '', False, ['Advanced/General']),
  ('max_error_count', '', True, ['Advanced/General']),
  ('max_execution_time', '', True, ['Advanced/Various']),
  ('max_heap_table_size', '', True, ['Advanced/Various']),
  ('max_insert_delayed_threads', '', True, []),
  ('max_join_size', '', True, ['Advanced/Various']),
  ('max_length_for_sort_data', '', True, ['Advanced/Various']),
  ('max_long_data_size', '', False, ['General/General']),
  ('max_points_in_geometry', '', True, ['Advanced/Various']),
  ('max_prepared_stmt_count', '', True, ['Advanced/General']),
  ('max_relay_log_size', '', True, ['Replication/Relay Log']),
  ('max_seeks_for_key', '', True, ['Advanced/Various']),
  ('max_sort_length', '', True, ['Advanced/Various']),
  ('max_sp_recursion_depth', '', True, ['Advanced/General']),
  ('max_statement_time', '', True, []),
  ('max_tmp_tables', '', True, []),
  ('max_user_connections', '', True, ['Networking/Advanced']),
  ('max_write_lock_count', '', True, ['Advanced/Various']),
  ('mecab_rc_file', '', False, []),
  ('metadata_locks_cache_size', '', False, []),
  ('metadata_locks_hash_instances', '', False, []),
  ('min-examined-row-limit', '', True, []),
  ('multi_range_count', '', True, ['Advanced/Various']),
  ('myisam_data_pointer_size', '', True, ['MyISAM/Advanced Settings']),
  ('myisam_max_extra_sort_file_size', '', False, ['MyISAM/Advanced Settings']),
  ('myisam_max_sort_file_size', '', True, ['MyISAM/Advanced Settings']),
  ('myisam_mmap_size', '', False, ['MyISAM/Advanced Settings']),
  ('myisam_recover_options', '', False, []),
  ('myisam_repair_threads', '', True, ['MyISAM/Advanced Settings']),
  ('myisam_sort_buffer_size', '', True, ['MyISAM/Advanced Settings']),
  ('myisam_stats_method', '', True, ['MyISAM/Advanced Settings']),
  ('myisam_use_mmap', '', True, ['MyISAM/Advanced Settings']),
  ('mysql_native_password_proxy_users', '', True, []),
  ('mysql_firewall_max_query_size', '', False, ['General/Firewall']),
  ('mysql_firewall_mode', '', True, ['General/Firewall']),
  ('mysql_firewall_trace', '', True, ['General/Firewall']),
  ('named_pipe', '', False, []),
  ('ndb-batch-size', '', False, []),
  ('ndb-blob-read-batch-bytes', '', True, []),
  ('ndb-blob-write-batch-bytes', '', True, []),
  ('ndb-cluster-connection-pool', '', False, []),
  ('ndb-cluster-connection-pool-nodeids', '', False, []),
  ('ndb-deferred-constraints', '', True, ['Other/NDB']),
  ('ndb-distribution', '', True, ['Other/NDB']),
  ('ndb-log-apply-status', '', False, ['Other/NDB']),
  ('ndb-log-empty-epochs', '', True, ['Other/NDB']),
  ('ndb-log-exclusive-reads', '', True, ['Other/NDB']),
  ('ndb-log-orig', '', False, ['Other/NDB']),
  ('ndb-log-transaction-id', '', False, []),
  ('ndb-log-update-as-write', '', True, []),
  ('ndb-wait-connected', '', False, []),
  ('ndb-wait-setup', '', False, []),
  ('ndb-allow-copying-alter-table', '', True, []),
  ('ndb_autoincrement_prefetch_sz', '', True, ['Other/NDB']),
  ('ndb_cache_check_time', '', True, ['Other/NDB']),
  ('ndb_clear_apply_status', '', True, []),
  ('Ndb_conflict_last_conflict_epoch', '', False, []),
  ('ndb_deferred_constraints', '', True, ['Other/NDB']),
  ('ndb_distribution', '', True, ['Other/NDB']),
  ('ndb_eventbuffer_free_percent', '', True, ['Other/NDB']),
  ('ndb_eventbuffer_max_alloc', '', True, ['Other/NDB']),
  ('ndb_extra_logging', '', True, ['Other/NDB']),
  ('ndb_force_send', '', True, ['Other/NDB']),
  ('ndb_index_stat_cache_entries', '', True, ['Other/NDB']),
  ('ndb_index_stat_enable', '', True, ['Other/NDB']),
  ('ndb_index_stat_option', '', True, ['Other/NDB']),
  ('ndb_index_stat_update_freq', '', True, ['Other/NDB']),
  ('ndb_join_pushdown', '', True, []),
  ('ndb_log_apply_status', '', False, ['Other/NDB']),
  ('ndb_log_bin', '', True, []),
  ('ndb_log_binlog_index', '', True, []),
  ('ndb_log_empty_epochs', '', True, ['Other/NDB']),
  ('ndb_log_exclusive_reads', '', True, ['Other/NDB']),
  ('ndb_log_orig', '', False, ['Other/NDB']),
  ('ndb_log_transaction_id', '', False, []),
  ('ndb_log_updated_only', '', True, ['Other/NDB']),
  ('ndb_optimization_delay', '', True, []),
  ('ndb_optimized_node_selection', '', False, ['Other/NDB']),
  ('ndb_recv_thread_cpu_mask', '', True, []),
  ('ndb_show_foreign_key_mock_tables', '', True, ['Other/NDB']),
  ('ndb_slave_conflict_role', '', True, ['Other/NDB']),
  ('Ndb_slave_max_replicated_epoch', '', False, []),
  ('ndb_table_no_logging', '', True, []),
  ('ndb_table_temporary', '', True, []),
  ('ndb_use_copying_alter_table', '', False, []),
  ('ndb_use_exact_count', '', True, []),
  ('ndb_use_transactions', '', True, ['Other/NDB']),
  ('ndb_version', '', False, []),
  ('ndb_version_string', '', False, []),
  ('ndbinfo_database', '', False, []),
  ('ndbinfo_max_bytes', '', True, []),
  ('ndbinfo_max_rows', '', True, []),
  ('ndbinfo_offline', '', True, []),
  ('ndbinfo_show_hidden', '', True, []),
  ('ndbinfo_table_prefix', '', True, []),
  ('ndbinfo_version', '', False, []),
  ('net_buffer_length', '', True, ['Networking/Data / Memory size']),
  ('net_read_timeout', '', True, ['Networking/Timeout Settings']),
  ('net_retry_count', '', True, ['Networking/Advanced']),
  ('net_write_timeout', '', True, ['Networking/Timeout Settings']),
  ('new', '', True, ['Advanced/Various']),
  ('ngram_token_size', '', False, []),
  ('offline_mode', '', True, []),
  ('old', '', False, ['General/General']),
  ('old-alter-table', '', True, []),
  ('old_passwords', '', True, []),
  ('open-files-limit', '', False, []),
  ('optimizer_join_cache_level', '', True, ['Performance/Optimizer']),
  ('optimizer_prune_level', '', True, ['Performance/Optimizer']),
  ('optimizer_search_depth', '', True, ['Performance/Optimizer']),
  ('optimizer_switch', '', True, ['Performance/Optimizer']),
  ('optimizer_trace', '', True, []),
  ('optimizer_trace_features', '', True, []),
  ('optimizer_trace_limit', '', True, []),
  ('optimizer_trace_max_mem_size', '', True, []),
  ('optimizer_trace_offset', '', True, []),
  ('optimizer_use_mrr', '', True, []),
  ('parser_max_mem_size', '', True, []),
  ('performance_schema', '', False, ['Performance/Performance Schema']),
  ( 'performance_schema_accounts_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_digests_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_stages_history_long_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_stages_history_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_statements_history_long_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_statements_history_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_transactions_history_long_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_transactions_history_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_waits_history_long_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_events_waits_history_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_hosts_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_cond_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_cond_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_digest_length',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_file_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_file_handles',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_file_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_index_stat',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_memory_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_metadata_locks',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_mutex_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_mutex_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_prepared_statements_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_program_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_rwlock_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_rwlock_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_socket_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_socket_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_sql_text_length',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_stage_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_statement_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_statement_stack',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_table_handles',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_table_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_table_lock_stat',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_thread_classes',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_max_thread_instances',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_session_connect_attrs_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_setup_actors_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_setup_objects_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ( 'performance_schema_users_size',
    '',
    False,
    ['Performance/Performance Schema']),
  ('pid-file', '', False, []),
  ('plugin_dir', '', False, ['General/Directories']),
  ('port', '', False, ['Networking/General']),
  ('preload_buffer_size', '', True, ['Advanced/Various']),
  ('prepared_stmt_count', '', False, []),
  ('profiling', '', True, []),
  ( 'profiling_history_size',
    '',
    True,
    ['General/Features', 'Performance/General']),
  ('protocol_version', '', False, []),
  ('proxy_user', '', False, []),
  ('pseudo_slave_mode', '', True, []),
  ('pseudo_thread_id', '', True, []),
  ( 'query_alloc_block_size',
    '',
    True,
    ['Advanced/Various', 'General/Memory usage']),
  ('query_cache_limit', '', True, ['Performance/Query cache']),
  ('query_cache_min_res_unit', '', True, ['Performance/Query cache']),
  ('query_cache_size', '', True, ['Performance/Query cache']),
  ('query_cache_type', '', True, ['Performance/Query cache']),
  ('query_cache_wlock_invalidate', '', True, ['Performance/Query cache']),
  ('query_prealloc_size', '', True, ['Advanced/Various']),
  ('rand_seed1', '', True, []),
  ('rand_seed2', '', True, []),
  ('range_alloc_block_size', '', True, ['Advanced/Various']),
  ('range_optimizer_max_mem_size', '', True, ['Advanced/Various']),
  ('rbr_exec_mode', '', True, []),
  ('read_buffer_size', '', True, ['Advanced/Various']),
  ('read_only', '', True, ['Security/Security']),
  ('read_rnd_buffer_size', '', True, ['Advanced/Various']),
  ('relay-log', '', False, []),
  ('relay-log-index', '', False, ['Replication/Relay Log']),
  ('relay_log_basename', '', False, []),
  ('relay_log_index', '', False, ['Replication/Relay Log']),
  ('relay_log_info_file', '', False, ['Replication/Relay Log']),
  ('relay_log_info_repository', '', True, []),
  ('relay_log_purge', '', True, ['Replication/Relay Log']),
  ('relay_log_recovery', '', True, ['Replication/Relay Log']),
  ('relay_log_space_limit', '', False, ['Replication/Relay Log']),
  ('report-host', '', False, []),
  ('report-password', '', False, []),
  ('report-port', '', False, []),
  ('report-user', '', False, []),
  ('require_secure_transport', '', True, []),
  ('restore_disables_events', '', True, ['Advanced/General']),
  ('restore_elevation', '', False, ['Advanced/General']),
  ('restore_precheck', '', True, ['Advanced/General']),
  ('rewriter_enabled', '', True, []),
  ('rewriter_verbose', '', True, []),
  ('rpl_recovery_rank', '', True, []),
  ('rpl_semi_sync_master_enabled', '', True, []),
  ('rpl_semi_sync_master_reply_log_file_pos', '', True, []),
  ('rpl_semi_sync_master_timeout', '', True, []),
  ('rpl_semi_sync_master_trace_level', '', True, []),
  ('rpl_semi_sync_master_wait_for_slave_count', '', True, []),
  ('rpl_semi_sync_master_wait_no_slave', '', True, []),
  ('rpl_semi_sync_master_wait_point', '', True, []),
  ('rpl_semi_sync_slave_enabled', '', True, []),
  ('rpl_semi_sync_slave_trace_level', '', True, []),
  ('rpl_stop_slave_timeout', '', True, ['Replication/Slave']),
  ('safe-show-database', '', True, []),
  ('schema_definition_cache', '', True, ['Security/Security']),
  ('secure-auth', '', True, []),
  ('secure-backup-file-priv', '', False, []),
  ('secure-file-priv', '', False, []),
  ('server-id', '', True, []),
  ('server-id-bits', '', False, []),
  ('server_id_bits', '', False, []),
  ('server_uuid', '', False, []),
  ('session_track_gtids', '', True, ['General/General']),
  ('session_track_schema', '', True, ['General/General']),
  ('session_track_state_change', '', True, ['General/General']),
  ('session_track_system_variables', '', True, ['General/General']),
  ('sha256_password_auto_generate_rsa_keys', '', False, []),
  ('sha256_password_private_key_path', '', False, []),
  ('sha256_password_proxy_users', '', True, []),
  ('sha256_password_public_key_path', '', False, []),
  ('shared_memory', '', False, []),
  ('shared_memory_base_name', '', False, []),
  ('show_compatibility_56', '', True, []),
  ('show_old_temporals', '', True, []),
  ('simplified_binlog_gtid_recovery', '', False, []),
  ('skip-name-resolve', '', False, []),
  ('skip-networking', '', False, []),
  ('skip-show-database', '', False, []),
  ('skip-sync-bdb-logs', '', False, []),
  ('skip_external_locking', '', False, ['General/System']),
  ('slave-load-tmpdir', '', False, []),
  ('slave-net-timeout', '', True, []),
  ('slave-skip-errors', '', False, []),
  ('slave_allow_batching', '', True, ['Replication/Slave']),
  ('slave_checkpoint_group', '', True, ['Replication/Slave']),
  ('slave_checkpoint_period', '', True, ['Replication/Slave']),
  ('slave_compressed_protocol', '', True, ['Replication/Slave']),
  ('slave_exec_mode', '', True, ['Replication/Slave']),
  ('slave_max_allowed_packet', '', True, []),
  ('slave_parallel_type', '', True, []),
  ('slave_parallel_workers', '', True, []),
  ('slave_pending_jobs_size_max', '', True, []),
  ('slave_preserve_commit_order', '', True, []),
  ('slave_rows_search_algorithms', '', True, []),
  ('slave_sql_verify_checksum', '', True, []),
  ('slave_transaction_retries', '', True, ['Replication/Slave']),
  ('slave_type_conversions', '', False, ['Replication/Slave']),
  ('slow-query-log', '', True, []),
  ('slow_launch_time', '', True, ['Advanced/Thread specific settings']),
  ('slow_query_log_file', '', True, ['Logging/Slow query log options']),
  ('socket', '', False, ['Networking/General']),
  ('sort_buffer_size', '', True, ['General/Memory usage']),
  ('sql-mode', '', True, []),
  ('sql_auto_is_null', '', True, []),
  ('sql_big_selects', '', True, []),
  ('sql_big_tables', '', True, []),
  ('sql_buffer_result', '', True, []),
  ('sql_log_bin', '', True, []),
  ('sql_log_off', '', True, []),
  ('sql_log_update', '', True, []),
  ('sql_low_priority_updates', '', True, []),
  ('sql_max_join_size', '', True, []),
  ('sql_notes', '', True, []),
  ('sql_quote_show_create', '', True, []),
  ('sql_safe_updates', '', True, []),
  ('sql_select_limit', '', True, []),
  ('sql_slave_skip_counter', '', True, []),
  ('sql_warnings', '', True, []),
  ('ssl-ca', '', False, []),
  ('ssl-capath', '', False, []),
  ('ssl-cert', '', False, []),
  ('ssl-cipher', '', False, []),
  ('ssl-crl', '', False, []),
  ('ssl-crlpath', '', False, []),
  ('ssl-key', '', False, []),
  ('storage_engine', '', True, []),
  ('stored_program_cache', '', True, ['General/General']),
  ('stored_program_definition_cache', '', True, []),
  ('super_read_only', '', True, []),
  ('sync-bdb-logs', '', False, []),
  ('sync_binlog', '', True, ['Logging/Binlog Options']),
  ('sync_frm', '', True, ['Advanced/General']),
  ('sync_master_info', '', True, ['Replication/Master']),
  ('sync_relay_log', '', True, ['Replication/Relay Log']),
  ('sync_relay_log_info', '', True, ['Replication/Relay Log']),
  ('system_time_zone', '', False, []),
  ('tablespace_definition_cache', '', True, []),
  ('table_cache', '', True, []),
  ('table_definition_cache', '', True, []),
  ('table_lock_wait_timeout', '', True, []),
  ('table_open_cache', '', True, []),
  ('table_open_cache_instances', '', False, []),
  ('table_type', '', True, []),
  ('thread_cache_size', '', True, ['Advanced/Thread specific settings']),
  ('thread_concurrency', '', False, ['Advanced/Thread specific settings']),
  ('thread_handling', '', False, ['Advanced/Thread specific settings']),
  ('thread_pool_algorithm', '', False, ['Advanced/Thread specific settings']),
  ( 'thread_pool_high_priority_connection',
    '',
    True,
    ['Advanced/Thread specific settings']),
  ( 'thread_pool_max_unused_threads',
    '',
    True,
    ['Advanced/Thread specific settings']),
  ( 'thread_pool_prio_kickup_timer',
    '',
    True,
    ['Advanced/Thread specific settings']),
  ('thread_pool_size', '', False, ['Advanced/Thread specific settings']),
  ('thread_pool_stall_limit', '', True, ['Advanced/Thread specific settings']),
  ('thread_stack', '', False, ['Advanced/Thread specific settings']),
  ('time_format', '', False, []),
  ('time_zone', '', True, []),
  ('timed_mutexes', '', True, ['InnoDB/General']),
  ('timestamp', '', True, []),
  ('tls_version', '', False, []),
  ('tmp_table_size', '', True, ['Advanced/Various']),
  ('tmpdir', '', False, ['General/Directories']),
  ('transaction_alloc_block_size', '', True, ['Advanced/Transactions']),
  ('transaction_allow_batching', '', True, []),
  ('transaction_prealloc_size', '', True, ['Advanced/Transactions']),
  ('transaction_write_set_extraction', '', True, []),
  ('tx_isolation', '', True, []),
  ('tx_read_only', '', True, []),
  ('unique_checks', '', True, []),
  ('updatable_views_with_limit', '', True, ['Advanced/General']),
  ('validate_password_dictionary_file', '', True, []),
  ('validate_password_length', '', True, []),
  ('validate_password_mixed_case_count', '', True, []),
  ('validate_password_number_count', '', True, []),
  ('validate_password_policy', '', True, []),
  ('validate_password_special_char_count', '', True, []),
  ('validate_user_plugins', '', False, []),
  ('version', '', False, []),
  ('version_comment', '', False, []),
  ('version_compile_machine', '', False, []),
  ('version_compile_os', '', False, []),
  ('version_tokens_session', '', True, []),
  ('version_tokens_session_number', '', False, []),
  ('wait_timeout', '', True, ['Networking/Timeout Settings']),
  ('warning_count', '', False, [])]



status_variable_list = [ ('mysqlx_port', '', True, []),
  ('mysqlx_max_connections', '', True, []),
  ('mysqlx_initial_incoming_queue_bytes', '', True, []),
  ('Aborted_clients', '', False, ['Networking/Stats']),
  ('Aborted_connects', '', False, ['Networking/Stats']),
  ('Audit_log_current_size', '', False, ['General']),
  ('Audit_log_event_max_drop_size', '', False, ['General']),
  ('Audit_log_events', '', False, ['General']),
  ('Audit_log_events_filtered', '', False, ['General']),
  ('Audit_log_events_lost', '', False, ['General']),
  ('Audit_log_events_written', '', False, ['General']),
  ('Audit_log_total_size', '', False, ['General']),
  ('Audit_log_write_waits', '', False, ['General']),
  ('Binlog_cache_disk_use', '', False, ['Binlog']),
  ('Binlog_cache_use', '', False, ['Binlog']),
  ('Binlog_stmt_cache_disk_use', '', False, ['Binlog']),
  ('Binlog_stmt_cache_use', '', False, ['Binlog']),
  ('Bytes_received', '', False, ['Networking/Stats']),
  ('Bytes_sent', '', False, ['Networking/Stats']),
  ('Com_admin_commands', '', False, ['Commands/Admin']),
  ('Com_alter_db', '', False, ['Commands/DDL']),
  ('Com_alter_db_upgrade', '', False, ['Commands/DDL']),
  ('Com_alter_event', '', False, ['Commands/DDL']),
  ('Com_alter_function', '', False, ['Commands/DDL']),
  ('Com_alter_procedure', '', False, ['Commands/DDL']),
  ('Com_alter_server', '', False, ['Commands/DDL']),
  ('Com_alter_table', '', False, ['Commands/DDL']),
  ('Com_alter_tablespace', '', False, ['Commands/DDL']),
  ('Com_alter_user', '', False, ['Commands/Admin']),
  ('Com_analyze', '', False, ['Commands/General']),
  ('Com_assign_to_keycache', '', False, ['Commands/General']),
  ('Com_backup', '', False, []),
  ('Com_backup_table', '', False, []),
  ('Com_begin', '', False, ['Commands/Transaction']),
  ('Com_binlog', '', False, ['Binlog', 'Commands/General']),
  ('Com_call_procedure', '', False, ['Commands/DML']),
  ('Com_change_db', '', False, ['Commands/General']),
  ('Com_change_master', '', False, ['Commands/Admin']),
  ('Com_change_repl_filter', '', False, []),
  ('Com_check', '', False, ['Commands/Admin']),
  ('Com_checksum', '', False, ['Commands/General']),
  ('Com_commit', '', False, ['Commands/General']),
  ('Com_create_db', '', False, ['Commands/DDL']),
  ('Com_create_event', '', False, ['Commands/DDL']),
  ('Com_create_function', '', False, ['Commands/DDL']),
  ('Com_create_index', '', False, ['Commands/DDL']),
  ('Com_create_procedure', '', False, ['Commands/DDL']),
  ('Com_create_server', '', False, ['Commands/DDL']),
  ('Com_create_table', '', False, ['Commands/DDL']),
  ('Com_create_trigger', '', False, ['Commands/DDL']),
  ('Com_create_udf', '', False, ['Commands/Admin']),
  ('Com_create_user', '', False, ['Commands/Admin']),
  ('Com_create_view', '', False, ['Commands/DDL']),
  ('Com_dealloc_sql', '', False, ['Commands/DML']),
  ('Com_delete', '', False, ['Commands/DML']),
  ('Com_delete_multi', '', False, ['Commands/DML']),
  ('Com_do', '', False, ['Commands/DML']),
  ('Com_drop_db', '', False, ['Commands/DDL']),
  ('Com_drop_event', '', False, ['Commands/DDL']),
  ('Com_drop_function', '', False, ['Commands/DDL']),
  ('Com_drop_index', '', False, ['Commands/DDL']),
  ('Com_drop_procedure', '', False, ['Commands/DDL']),
  ('Com_drop_server', '', False, ['Commands/DDL']),
  ('Com_drop_table', '', False, ['Commands/DDL']),
  ('Com_drop_trigger', '', False, ['Commands/DDL']),
  ('Com_drop_user', '', False, ['Commands/DDL']),
  ('Com_drop_view', '', False, ['Commands/DDL']),
  ('Com_empty_query', '', False, ['Commands/General']),
  ('Com_execute_sql', '', False, ['Commands/General']),
  ('Com_explain_other', '', False, ['Commands/General']),
  ('Com_flush', '', False, ['Commands/General']),
  ('Com_get_diagnostics', '', False, ['Commands/Admin']),
  ('Com_grant', '', False, ['Commands/Admin']),
  ('Com_ha_close', '', False, ['Commands/Admin']),
  ('Com_ha_open', '', False, ['Commands/Admin']),
  ('Com_ha_read', '', False, ['Commands/Admin']),
  ('Com_help', '', False, ['Commands/General']),
  ('Com_insert', '', False, ['Commands/DML']),
  ('Com_insert_select', '', False, ['Commands/DML']),
  ('Com_install_plugin', '', False, ['Commands/Admin']),
  ('Com_kill', '', False, ['Commands/Admin']),
  ('Com_load', '', False, ['Commands/Admin']),
  ('Com_load_master_data', '', False, ['Commands/Admin']),
  ('Com_load_master_table', '', False, ['Commands/Admin']),
  ('Com_lock_tables', '', False, ['Commands/General']),
  ('Com_optimize', '', False, ['Commands/Admin']),
  ('Com_preload_keys', '', False, ['Commands/Admin']),
  ('Com_prepare_sql', '', False, ['Commands/DML']),
  ('Com_purge', '', False, ['Commands/Admin']),
  ('Com_purge_before_date', '', False, ['Commands/Admin']),
  ('Com_purge_bup_log', '', False, ['Commands/Admin']),
  ('Com_release_savepoint', '', False, ['Commands/Admin']),
  ('Com_rename_table', '', False, ['Commands/DDL']),
  ('Com_rename_user', '', False, ['Commands/Admin']),
  ('Com_repair', '', False, ['Commands/Admin']),
  ('Com_replace', '', False, ['Commands/DML']),
  ('Com_replace_select', '', False, ['Commands/DML']),
  ('Com_reset', '', False, ['Commands/Admin']),
  ('Com_resignal', '', False, ['Commands/Admin']),
  ('Com_restore', '', False, ['Commands/Admin']),
  ('Com_restore_table', '', False, ['Commands/Admin']),
  ('Com_revoke', '', False, ['Commands/Admin']),
  ('Com_revoke_all', '', False, ['Commands/Admin']),
  ('Com_rollback', '', False, ['Commands/Transaction']),
  ('Com_rollback_to_savepoint', '', False, ['Commands/Transaction']),
  ('Com_savepoint', '', False, ['Commands/Transaction']),
  ('Com_select', '', False, ['Commands/General']),
  ('Com_set_option', '', False, ['Commands/General']),
  ('Com_show_authors', '', False, ['Commands/Show']),
  ('Com_show_binlog_events', '', False, ['Commands/Show']),
  ('Com_show_binlogs', '', False, ['Commands/Show']),
  ('Com_show_charsets', '', False, ['Commands/Show']),
  ('Com_show_collations', '', False, ['Commands/Show']),
  ('Com_show_column_types', '', False, ['Commands/Show']),
  ('Com_show_contributors', '', False, ['Commands/Show']),
  ('Com_show_create_db', '', False, ['Commands/Show']),
  ('Com_show_create_event', '', False, ['Commands/Show']),
  ('Com_show_create_func', '', False, ['Commands/Show']),
  ('Com_show_create_proc', '', False, ['Commands/Show']),
  ('Com_show_create_table', '', False, ['Commands/Show']),
  ('Com_show_create_trigger', '', False, ['Commands/Show']),
  ('Com_show_create_user', '', False, ['Commands/Show']),
  ('Com_show_databases', '', False, ['Commands/Show']),
  ('Com_show_engine_logs', '', False, ['Commands/Show']),
  ('Com_show_engine_mutex', '', False, ['Commands/Show']),
  ('Com_show_engine_status', '', False, ['Commands/Show']),
  ('Com_show_errors', '', False, ['Commands/Show']),
  ('Com_show_events', '', False, ['Commands/Show']),
  ('Com_show_fields', '', False, ['Commands/Show']),
  ('Com_show_function_code', '', False, ['Commands/Show']),
  ('Com_show_function_status', '', False, ['Commands/Show']),
  ('Com_show_grants', '', False, ['Commands/Show']),
  ('Com_show_innodb_status', '', False, ['Commands/Show']),
  ('Com_show_keys', '', False, ['Commands/Show']),
  ('Com_show_logs', '', False, ['Commands/Show']),
  ('Com_show_master_status', '', False, ['Commands/Show']),
  ('Com_show_ndb_status', '', False, ['Commands/Show']),
  ('Com_show_new_master', '', False, ['Commands/Show']),
  ('Com_show_open_tables', '', False, ['Commands/Show']),
  ('Com_show_plugins', '', False, ['Commands/Show']),
  ('Com_show_privileges', '', False, ['Commands/Show']),
  ('Com_show_procedure_code', '', False, ['Commands/Show']),
  ('Com_show_procedure_status', '', False, ['Commands/Show']),
  ('Com_show_processlist', '', False, ['Commands/Show']),
  ('Com_show_profile', '', False, ['Commands/Show']),
  ('Com_show_profiles', '', False, ['Commands/Show']),
  ('Com_show_relaylog_events', '', False, ['Commands/Show']),
  ('Com_show_slave_hosts', '', False, ['Commands/Show']),
  ('Com_show_slave_status', '', False, ['Commands/Show']),
  ('Com_show_slave_status_nonblocking', '', False, ['Commands/Show']),
  ('Com_show_status', '', False, ['Commands/Show']),
  ('Com_show_storage_engines', '', False, ['Commands/Show']),
  ('Com_show_table_status', '', False, ['Commands/Show']),
  ('Com_show_tables', '', False, ['Commands/Show']),
  ('Com_show_triggers', '', False, ['Commands/Show']),
  ('Com_show_variables', '', False, ['Commands/Show']),
  ('Com_show_warnings', '', False, ['Commands/Show']),
  ('Com_shutdown', '', False, ['Commands/Show']),
  ('Com_signal', '', False, ['Commands/Admin']),
  ('Com_slave_start', '', False, ['Commands/Replication']),
  ('Com_slave_stop', '', False, ['Commands/Replication']),
  ('Com_stmt_close', '', False, ['Commands/Prepared Statement']),
  ('Com_stmt_execute', '', False, ['Commands/Prepared Statement']),
  ('Com_stmt_fetch', '', False, ['Commands/Prepared Statement']),
  ('Com_stmt_prepare', '', False, ['Commands/Prepared Statement']),
  ('Com_stmt_reprepare', '', False, ['Commands/Prepared Statement']),
  ('Com_stmt_reset', '', False, ['Commands/Prepared Statement']),
  ('Com_stmt_send_long_data', '', False, ['Commands/Prepared Statement']),
  ('Com_truncate', '', False, ['Commands/DML']),
  ('Com_uninstall_plugin', '', False, ['Commands/Admin']),
  ('Com_unlock_tables', '', False, ['Commands/Admin']),
  ('Com_update', '', False, ['Commands/DML']),
  ('Com_update_multi', '', False, ['Commands/DML']),
  ('Com_xa_commit', '', False, ['Commands/Transaction']),
  ('Com_xa_end', '', False, ['Commands/Transaction']),
  ('Com_xa_prepare', '', False, ['Commands/Transaction']),
  ('Com_xa_recover', '', False, ['Commands/Transaction']),
  ('Com_xa_rollback', '', False, ['Commands/Transaction']),
  ('Com_xa_start', '', False, ['Commands/Transaction']),
  ('Compression', '', False, ['General']),
  ('Connection_errors_accept', '', False, ['Networking/Errors']),
  ('Connection_errors_internal', '', False, ['Networking/Errors']),
  ('Connection_errors_max_connections', '', False, ['Networking/Errors']),
  ('Connection_errors_peer_addr', '', False, ['Networking/Errors']),
  ('Connection_errors_select', '', False, ['Networking/Errors']),
  ('Connection_errors_tcpwrap', '', False, ['Networking/Errors']),
  ('Connections', '', False, ['Networking/Stats']),
  ('Created_tmp_disk_tables', '', False, ['General']),
  ('Created_tmp_files', '', False, ['General']),
  ('Created_tmp_tables', '', False, ['General']),
  ('Delayed_errors', '', False, ['General']),
  ('Delayed_insert_threads', '', False, ['General']),
  ('Delayed_writes', '', False, ['General']),
  ('Firewall_access_denied', '', False, ['Firewall']),
  ('Firewall_access_granted', '', False, ['Firewall']),
  ('Firewall_cached_entries', '', False, ['Firewall']),
  ('Flush_commands', '', False, ['General']),
  ('Handler_commit', '', False, ['Handler']),
  ('Handler_delete', '', False, ['Handler']),
  ('Handler_discover', '', False, ['Handler']),
  ('Handler_external_lock', '', False, ['Handler']),
  ('Handler_mrr_init', '', False, ['Handler']),
  ('Handler_prepare', '', False, ['Handler']),
  ('Handler_read_first', '', False, ['Handler']),
  ('Handler_read_key', '', False, ['Handler']),
  ('Handler_read_last', '', False, ['Handler']),
  ('Handler_read_next', '', False, ['Handler']),
  ('Handler_read_prev', '', False, ['Handler']),
  ('Handler_read_rnd', '', False, ['Handler']),
  ('Handler_read_rnd_next', '', False, ['Handler']),
  ('Handler_rollback', '', False, ['Handler']),
  ('Handler_savepoint', '', False, ['Handler']),
  ('Handler_savepoint_rollback', '', False, ['Handler']),
  ('Handler_update', '', False, ['Handler']),
  ('Handler_write', '', False, ['Handler']),
  ('Innodb_available_undo_logs', '', False, ['InnoDB/Stats']),
  ('Innodb_buffer_pool_bytes_data', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_bytes_dirty', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_dump_status', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_load_status', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_pages_data', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_pages_dirty', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_pages_flushed', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_pages_free', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_pages_latched', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_pages_misc', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_pages_total', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_read_ahead', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_read_ahead_evicted', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_read_ahead_rnd', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_read_ahead_seq', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_read_requests', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_reads', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_resize_status', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_wait_free', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_buffer_pool_write_requests', '', False, ['InnoDB/Buffer pool']),
  ('Innodb_data_fsyncs', '', False, ['InnoDB/Data']),
  ('Innodb_data_pending_fsyncs', '', False, ['InnoDB/Data']),
  ('Innodb_data_pending_reads', '', False, ['InnoDB/Data']),
  ('Innodb_data_pending_writes', '', False, ['InnoDB/Data']),
  ('Innodb_data_read', '', False, ['InnoDB/Data', 'InnoDB/Stats']),
  ('Innodb_data_reads', '', False, ['InnoDB/Data', 'InnoDB/Stats']),
  ('Innodb_data_writes', '', False, ['InnoDB/Data', 'InnoDB/Stats']),
  ('Innodb_data_written', '', False, ['InnoDB/Data', 'InnoDB/Stats']),
  ('Innodb_dblwr_pages_written', '', False, ['InnoDB/General']),
  ('Innodb_dblwr_writes', '', False, ['InnoDB/General']),
  ('Innodb_have_atomic_builtins', '', False, ['InnoDB/General']),
  ('Innodb_have_sync_atomic', '', False, ['InnoDB/General']),
  ('Innodb_heap_enabled', '', False, ['InnoDB/General']),
  ('Innodb_log_waits', '', False, ['InnoDB/Stats']),
  ('Innodb_log_write_requests', '', False, ['InnoDB/Stats']),
  ('Innodb_log_writes', '', False, ['InnoDB/Stats']),
  ('Innodb_num_open_files', '', False, ['InnoDB/Stats']),
  ('Innodb_os_log_fsyncs', '', False, ['InnoDB/Stats']),
  ('Innodb_os_log_pending_fsyncs', '', False, ['InnoDB/Stats']),
  ('Innodb_os_log_pending_writes', '', False, ['InnoDB/Stats']),
  ('Innodb_os_log_written', '', False, ['InnoDB/Stats']),
  ('Innodb_page_size', '', False, ['InnoDB/Stats']),
  ('Innodb_pages_created', '', False, ['InnoDB/Stats']),
  ('Innodb_pages_read', '', False, ['InnoDB/Stats']),
  ('Innodb_pages_written', '', False, ['InnoDB/Stats']),
  ('Innodb_row_lock_current_waits', '', False, ['InnoDB/Stats']),
  ('Innodb_row_lock_time', '', False, ['InnoDB/Stats']),
  ('Innodb_row_lock_time_avg', '', False, ['InnoDB/Stats']),
  ('Innodb_row_lock_time_max', '', False, ['InnoDB/Stats']),
  ('Innodb_row_lock_waits', '', False, ['InnoDB/Stats']),
  ('Innodb_rows_deleted', '', False, ['InnoDB/Stats']),
  ('Innodb_rows_inserted', '', False, ['InnoDB/Stats']),
  ('Innodb_rows_read', '', False, ['InnoDB/Stats']),
  ('Innodb_rows_updated', '', False, ['InnoDB/Stats']),
  ('Innodb_truncated_status_writes', '', False, ['InnoDB/Stats']),
  ('Innodb_wake_ups', '', False, ['InnoDB/Stats']),
  ('Key_blocks_not_flushed', '', False, ['Keycache']),
  ('Key_blocks_unused', '', False, ['Keycache']),
  ('Key_blocks_used', '', False, ['Keycache']),
  ('Key_read_requests', '', False, ['Keycache']),
  ('Key_reads', '', False, ['Keycache']),
  ('Key_write_requests', '', False, ['Keycache']),
  ('Key_writes', '', False, ['Keycache']),
  ('Last_query_cost', '', False, ['Performance']),
  ('Last_query_partial_plans', '', False, ['Performance']),
  ('Locked_connects', '', False, ['Networking/Stats']),
  ('Max_execution_time_exceeded', '', False, ['Networking/Stats']),
  ('Max_execution_time_set', '', False, ['Networking/Stats']),
  ('Max_execution_time_set_failed', '', False, ['Networking/Stats']),
  ('Max_statement_time_exceeded', '', False, ['Networking/Stats']),
  ('Max_statement_time_set', '', False, ['Networking/Stats']),
  ('Max_statement_time_set_failed', '', False, ['Networking/Stats']),
  ('Max_used_connections', '', False, ['Networking/Stats']),
  ('Max_used_connections_time', '', False, ['Networking/Stats']),
  ('mecab_charset', '', False, []),
  ('ndb-nodeid', '', False, []),
  ('Ndb_api_bytes_received_count', '', False, ['NDB']),
  ('Ndb_api_bytes_received_count_session', '', False, ['NDB']),
  ('Ndb_api_bytes_received_count_slave', '', False, ['NDB']),
  ('Ndb_api_bytes_sent_count', '', False, ['NDB']),
  ('Ndb_api_bytes_sent_count_session', '', False, ['NDB']),
  ('Ndb_api_bytes_sent_count_slave', '', False, ['NDB']),
  ('Ndb_api_event_bytes_count', '', False, ['NDB']),
  ('Ndb_api_event_bytes_count_injector', '', False, ['NDB']),
  ('Ndb_api_event_data_count', '', False, ['NDB']),
  ('Ndb_api_event_data_count_injector', '', False, ['NDB']),
  ('Ndb_api_event_nondata_count', '', False, ['NDB']),
  ('Ndb_api_event_nondata_count_injector', '', False, ['NDB']),
  ('Ndb_api_pk_op_count', '', False, ['NDB']),
  ('Ndb_api_pk_op_count_session', '', False, ['NDB']),
  ('Ndb_api_pk_op_count_slave', '', False, ['NDB']),
  ('Ndb_api_pruned_scan_count', '', False, ['NDB']),
  ('Ndb_api_pruned_scan_count_session', '', False, ['NDB']),
  ('Ndb_api_pruned_scan_count_slave', '', False, ['NDB']),
  ('Ndb_api_range_scan_count', '', False, ['NDB']),
  ('Ndb_api_range_scan_count_session', '', False, ['NDB']),
  ('Ndb_api_range_scan_count_slave', '', False, ['NDB']),
  ('Ndb_api_read_row_count', '', False, ['NDB']),
  ('Ndb_api_read_row_count_session', '', False, ['NDB']),
  ('Ndb_api_read_row_count_slave', '', False, ['NDB']),
  ('Ndb_api_scan_batch_count', '', False, ['NDB']),
  ('Ndb_api_scan_batch_count_session', '', False, ['NDB']),
  ('Ndb_api_scan_batch_count_slave', '', False, ['NDB']),
  ('Ndb_api_table_scan_count', '', False, ['NDB']),
  ('Ndb_api_table_scan_count_session', '', False, ['NDB']),
  ('Ndb_api_table_scan_count_slave', '', False, ['NDB']),
  ('Ndb_api_trans_abort_count', '', False, ['NDB']),
  ('Ndb_api_trans_abort_count_session', '', False, ['NDB']),
  ('Ndb_api_trans_abort_count_slave', '', False, ['NDB']),
  ('Ndb_api_trans_close_count', '', False, ['NDB']),
  ('Ndb_api_trans_close_count_session', '', False, ['NDB']),
  ('Ndb_api_trans_close_count_slave', '', False, ['NDB']),
  ('Ndb_api_trans_commit_count', '', False, ['NDB']),
  ('Ndb_api_trans_commit_count_session', '', False, ['NDB']),
  ('Ndb_api_trans_commit_count_slave', '', False, ['NDB']),
  ('Ndb_api_trans_local_read_row_count', '', False, ['NDB']),
  ('Ndb_api_trans_local_read_row_count_session', '', False, ['NDB']),
  ('Ndb_api_trans_local_read_row_count_slave', '', False, ['NDB']),
  ('Ndb_api_trans_start_count', '', False, ['NDB']),
  ('Ndb_api_trans_start_count_session', '', False, ['NDB']),
  ('Ndb_api_trans_start_count_slave', '', False, ['NDB']),
  ('Ndb_api_uk_op_count', '', False, ['NDB']),
  ('Ndb_api_uk_op_count_session', '', False, ['NDB']),
  ('Ndb_api_uk_op_count_slave', '', False, ['NDB']),
  ('Ndb_api_wait_exec_complete_count', '', False, ['NDB']),
  ('Ndb_api_wait_exec_complete_count_session', '', False, ['NDB']),
  ('Ndb_api_wait_exec_complete_count_slave', '', False, ['NDB']),
  ('Ndb_api_wait_meta_request_count', '', False, ['NDB']),
  ('Ndb_api_wait_meta_request_count_session', '', False, ['NDB']),
  ('Ndb_api_wait_meta_request_count_slave', '', False, ['NDB']),
  ('Ndb_api_wait_nanos_count', '', False, ['NDB']),
  ('Ndb_api_wait_nanos_count_session', '', False, ['NDB']),
  ('Ndb_api_wait_nanos_count_slave', '', False, ['NDB']),
  ('Ndb_api_wait_scan_result_count', '', False, ['NDB']),
  ('Ndb_api_wait_scan_result_count_session', '', False, ['NDB']),
  ('Ndb_api_wait_scan_result_count_slave', '', False, ['NDB']),
  ('Ndb_cluster_node_id', '', False, ['NDB']),
  ('Ndb_config_from_host', '', False, ['NDB']),
  ('Ndb_config_from_port', '', False, ['NDB']),
  ('Ndb_conflict_fn_epoch', '', False, ['NDB']),
  ('Ndb_conflict_fn_epoch2', '', False, ['NDB']),
  ('Ndb_conflict_fn_epoch2_trans', '', False, ['NDB']),
  ('Ndb_conflict_fn_epoch_trans', '', False, ['NDB']),
  ('Ndb_conflict_fn_max', '', False, ['NDB']),
  ('Ndb_conflict_fn_max_del_win', '', False, ['NDB']),
  ('Ndb_conflict_fn_old', '', False, ['NDB']),
  ('Ndb_conflict_last_stable_epoch', '', False, ['NDB']),
  ('Ndb_conflict_reflected_op_discard_count', '', False, ['NDB']),
  ('Ndb_conflict_reflected_op_prepare_count', '', False, ['NDB']),
  ('Ndb_conflict_refresh_op_count', '', False, ['NDB']),
  ('Ndb_conflict_trans_conflict_commit_count', '', False, ['NDB']),
  ('Ndb_conflict_trans_detect_iter_count', '', False, ['NDB']),
  ('Ndb_conflict_trans_reject_count', '', False, ['NDB']),
  ('Ndb_conflict_trans_row_conflict_count', '', False, ['NDB']),
  ('Ndb_conflict_trans_row_reject_count', '', False, ['NDB']),
  ('Ndb_epoch_delete_delete_count', '', False, ['NDB']),
  ('Ndb_execute_count', '', False, ['NDB']),
  ('Ndb_last_commit_epoch_server', '', False, ['NDB']),
  ('Ndb_last_commit_epoch_session', '', False, ['NDB']),
  ('Ndb_number_of_data_nodes', '', False, ['NDB']),
  ('Ndb_pruned_scan_count', '', False, ['NDB']),
  ('Ndb_pushed_queries_defined', '', False, ['NDB']),
  ('Ndb_pushed_queries_dropped', '', False, ['NDB']),
  ('Ndb_pushed_queries_executed', '', False, ['NDB']),
  ('Ndb_pushed_reads', '', False, ['NDB']),
  ('ndb_recv_thread_activation_threshold', '', False, ['NDB']),
  ('Ndb_scan_count', '', False, ['NDB']),
  ('Not_flushed_delayed_rows', '', False, ['General']),
  ('Ongoing_anonymous_gtid_violating_transaction_count', '', False, []),
  ('Ongoing_anonymous_transaction_count', '', False, []),
  ('Ongoing_automatic_gtid_violating_transaction_count', '', False, []),
  ('Open_files', '', False, ['General']),
  ('Open_streams', '', False, ['General']),
  ('Open_table_definitions', '', False, ['General']),
  ('Open_tables', '', False, ['General']),
  ('Opened_files', '', False, ['General']),
  ('Opened_table_definitions', '', False, ['General']),
  ('Opened_tables', '', False, ['General']),
  ('Performance_schema_accounts_lost', '', False, ['Performance schema']),
  ('Performance_schema_cond_classes_lost', '', False, ['Performance schema']),
  ( 'Performance_schema_cond_instances_lost',
    '',
    False,
    ['Performance schema']),
  ('Performance_schema_digest_lost', '', False, ['Performance schema']),
  ('Performance_schema_file_classes_lost', '', False, ['Performance schema']),
  ('Performance_schema_file_handles_lost', '', False, ['Performance schema']),
  ( 'Performance_schema_file_instances_lost',
    '',
    False,
    ['Performance schema']),
  ('Performance_schema_hosts_lost', '', False, ['Performance schema']),
  ('Performance_schema_index_stat_lost', '', False, ['Performance schema']),
  ('Performance_schema_locker_lost', '', False, ['Performance schema']),
  ( 'Performance_schema_memory_classes_lost',
    '',
    False,
    ['Performance schema']),
  ('Performance_schema_metadata_lock_lost', '', False, ['Performance schema']),
  ('Performance_schema_mutex_classes_lost', '', False, ['Performance schema']),
  ( 'Performance_schema_mutex_instances_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_nested_statement_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_prepared_statements_lost',
    '',
    False,
    ['Performance schema']),
  ('Performance_schema_program_lost', '', False, ['Performance schema']),
  ( 'Performance_schema_rwlock_classes_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_rwlock_instances_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_session_connect_attrs_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_socket_classes_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_socket_instances_lost',
    '',
    False,
    ['Performance schema']),
  ('Performance_schema_stage_classes_lost', '', False, ['Performance schema']),
  ( 'Performance_schema_statement_classes_lost',
    '',
    False,
    ['Performance schema']),
  ('Performance_schema_table_handles_lost', '', False, ['Performance schema']),
  ( 'Performance_schema_table_instances_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_table_lock_stat_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_thread_classes_lost',
    '',
    False,
    ['Performance schema']),
  ( 'Performance_schema_thread_instances_lost',
    '',
    False,
    ['Performance schema']),
  ('Performance_schema_users_lost', '', False, ['Performance schema']),
  ('Prepared_stmt_count', '', False, ['General']),
  ('Qcache_free_blocks', '', False, ['Query cache']),
  ('Qcache_free_memory', '', False, ['Query cache']),
  ('Qcache_hits', '', False, ['Query cache']),
  ('Qcache_inserts', '', False, ['Query cache']),
  ('Qcache_lowmem_prunes', '', False, ['Query cache']),
  ('Qcache_not_cached', '', False, ['Query cache']),
  ('Qcache_queries_in_cache', '', False, ['Query cache']),
  ('Qcache_total_blocks', '', False, ['Query cache']),
  ('Queries', '', False, ['General']),
  ('Questions', '', False, ['General']),
  ('Rewriter_number_loaded_rules', '', False, []),
  ('Rewriter_number_reloads', '', False, []),
  ('Rewriter_number_rewritten_queries', '', False, []),
  ('Rewriter_reload_error', '', False, []),
  ('Rpl_semi_sync_master_clients', '', False, ['Commands/Replication']),
  ( 'Rpl_semi_sync_master_net_avg_wait_time',
    '',
    False,
    ['Commands/Replication']),
  ('Rpl_semi_sync_master_net_wait_time', '', False, ['Commands/Replication']),
  ('Rpl_semi_sync_master_net_waits', '', False, ['Commands/Replication']),
  ('Rpl_semi_sync_master_no_times', '', False, ['Commands/Replication']),
  ('Rpl_semi_sync_master_no_tx', '', False, ['Commands/Replication']),
  ('Rpl_semi_sync_master_status', '', False, ['Commands/Replication']),
  ( 'Rpl_semi_sync_master_timefunc_failures',
    '',
    False,
    ['Commands/Replication']),
  ( 'Rpl_semi_sync_master_tx_avg_wait_time',
    '',
    False,
    ['Commands/Replication']),
  ('Rpl_semi_sync_master_tx_wait_time', '', False, ['Commands/Replication']),
  ('Rpl_semi_sync_master_tx_waits', '', False, ['Commands/Replication']),
  ( 'Rpl_semi_sync_master_wait_pos_backtraverse',
    '',
    False,
    ['Commands/Replication']),
  ('Rpl_semi_sync_master_wait_sessions', '', False, ['Commands/Replication']),
  ('Rpl_semi_sync_master_yes_tx', '', False, ['Commands/Replication']),
  ('Rpl_semi_sync_slave_status', '', False, ['Commands/Replication']),
  ('Rpl_status', '', False, ['Commands/Replication']),
  ('Rsa_public_key', '', False, []),
  ('Select_full_join', '', False, ['General']),
  ('Select_full_range_join', '', False, ['General']),
  ('Select_range', '', False, ['General']),
  ('Select_range_check', '', False, ['General']),
  ('Select_scan', '', False, ['General']),
  ('Slave_heartbeat_period', '', False, ['Replication']),
  ('Slave_last_heartbeat', '', False, ['Replication']),
  ('Slave_open_temp_tables', '', False, ['Replication']),
  ('Slave_received_heartbeats', '', False, ['Replication']),
  ('Slave_retried_transactions', '', False, ['Replication']),
  ('Slave_running', '', False, ['Replication']),
  ('Slow_launch_threads', '', False, ['Threading']),
  ('Slow_queries', '', False, ['General']),
  ('Sort_merge_passes', '', False, ['General']),
  ('Sort_range', '', False, ['General']),
  ('Sort_rows', '', False, ['General']),
  ('Sort_scan', '', False, ['General']),
  ('Ssl_accept_renegotiates', '', False, ['SSL']),
  ('Ssl_accepts', '', False, ['SSL']),
  ('Ssl_callback_cache_hits', '', False, ['SSL']),
  ('Ssl_cipher', '', False, ['SSL']),
  ('Ssl_cipher_list', '', False, ['SSL']),
  ('Ssl_client_connects', '', False, ['SSL']),
  ('Ssl_connect_renegotiates', '', False, ['SSL']),
  ('Ssl_ctx_verify_depth', '', False, ['SSL']),
  ('Ssl_ctx_verify_mode', '', False, ['SSL']),
  ('Ssl_default_timeout', '', False, ['SSL']),
  ('Ssl_finished_accepts', '', False, ['SSL']),
  ('Ssl_finished_connects', '', False, ['SSL']),
  ('Ssl_server_not_after', '', False, ['SSL']),
  ('Ssl_server_not_before', '', False, ['SSL']),
  ('Ssl_session_cache_hits', '', False, ['SSL']),
  ('Ssl_session_cache_misses', '', False, ['SSL']),
  ('Ssl_session_cache_mode', '', False, ['SSL']),
  ('Ssl_session_cache_overflows', '', False, ['SSL']),
  ('Ssl_session_cache_size', '', False, ['SSL']),
  ('Ssl_session_cache_timeouts', '', False, ['SSL']),
  ('Ssl_sessions_reused', '', False, ['SSL']),
  ('Ssl_used_session_cache_entries', '', False, ['SSL']),
  ('Ssl_verify_depth', '', False, ['SSL']),
  ('Ssl_verify_mode', '', False, ['SSL']),
  ('Ssl_version', '', False, ['SSL']),
  ('Table_locks_immediate', '', False, ['General']),
  ('Table_locks_waited', '', False, ['General']),
  ('Table_open_cache_hits', '', False, ['General']),
  ('Table_open_cache_misses', '', False, ['General']),
  ('Table_open_cache_overflows', '', False, ['General']),
  ('Tc_log_max_pages_used', '', False, ['General']),
  ('Tc_log_page_size', '', False, ['General']),
  ('Tc_log_page_waits', '', False, ['General']),
  ('Threads_cached', '', False, ['Threading']),
  ('Threads_connected', '', False, ['Threading']),
  ('Threads_created', '', False, ['Threading']),
  ('Threads_running', '', False, ['Threading']),
  ('Uptime', '', False, ['General']),
  ('Uptime_since_flush_status', '', False, ['General']),
  ('validate_password_dictionary_file_last_parsed', '', False, []),
  ('validate_password_dictionary_file_words_count', '', False, [])]
